# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0002_auto_20180427_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Please use Charatater only', max_length=60, verbose_name='Person Name'),
        ),
    ]
