# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0006_auto_20180427_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='mymodel.Membership', to='mymodel.Mperson'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.Mperson'),
        ),
    ]
